sudo: false
addons:
  apt_packages:
  - libgl1-mesa-dev
  - libasound2-dev
  - xorg-dev
branches:
  only:
  - master
language: go
go_import_path: engo.io/engo
go:
- "1.10"
before_install: ./.before_install.sh
install:
-
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: ./.runtests.sh
matrix:
  include:
#   - env: TEST_TYPE=android_test
    - env: TEST_TYPE=android_build
    - env: TEST_TYPE=linux_test
    - env: TEST_TYPE=linux_build
    - env: TEST_TYPE=js_test
    - env: TEST_TYPE=js_build
    - env: TEST_TYPE=traffic_manager
env:
  global:
    secure: BVZrmTzkg/CPF6QDsQWyh/K+bd4yU3N3PFzcERaO6i32ln+uqaejhMtCsTXrr439vKH33DF5BFG34W+K4IbqwQyBgzjzUnotPXcWtXSuiojSOmCWkuw8qiPBuVTAsahBhP6N11LgUAcgkfAl968CkfIN3I7gBF916PFsefZtn6s=
