version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\engo.io\engo

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
